import type { Metadata } from "next";

import FooterSection from "@/components/landing-pages/sections/footer";
import { JsonLdSEO } from "@/components/layout/seo/jsonld-seo";
import { buildMetadataSEO, SEO_DEFAULTS } from "@/components/layout/seo/metadata-seo";
import { Container } from "@/components/ui/container";

const CANONICAL_PATH = "/terms-of-service";
const CANONICAL_URL = `${SEO_DEFAULTS.siteUrl}/terms-of-service`;

export const metadata: Metadata = buildMetadataSEO({
  type: "website",
  title: "Terms of Service",
  description:
    "These Terms of Service outline the agreement between you and Worklient regarding your use of our website and services.",
  canonicalPath: CANONICAL_PATH,
  keywords: [
    "terms of service",
    "website terms",
    "service agreement",
    "legal agreement",
  ],
});

export default function TermsOfService() {
  return (
    <>
      <Container className="sm:px-5 md:px-10 !py-30 flex flex-col gap-5">

        <h1 className="text-h3 lg:text-h2">Terms of Service</h1>
        <p className="text-body lg:text-body-lg">Last updated: February 20, 2026</p>

        <h2 className="text-body-lg lg:text-h3">1. Acceptance of Terms</h2>
        <p className="text-body lg:text-body-lg">These Terms of Service govern access to and use of the Worklient platform and related services. By creating an account, accessing the platform, or using any part of the service, you agree to be legally bound by these Terms. If you are using the service on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms.</p>

        <h2 className="text-body-lg lg:text-h3">2. Description of the Service</h2>
        <p className="text-body lg:text-body-lg">Worklient provides a campaign approval platform that enables organizations to manage structured review workflows, upload and version creative assets, track approval status, and maintain audit records of review activity. The service facilitates collaboration between internal organization members and external reviewers through secure access links. Worklient does not create client accounts for reviewers and limits reviewer access to the scope defined by the organization sharing content.</p>

        <h2 className="text-body-lg lg:text-h3">3. Eligibility</h2>
        <p className="text-body lg:text-body-lg">You must be at least eighteen years old and legally capable of entering into binding agreements to use the service. By using Worklient, you confirm that you meet these requirements and that all information provided during registration is accurate and complete.</p>

        <h2 className="text-body-lg lg:text-h3">4. Organization Accounts and Responsibilities</h2>
        <p className="text-body lg:text-body-lg">An organization account represents a business entity responsible for managing its internal users, permissions, and shared content. The organization is solely responsible for activities conducted under its account, including actions taken by invited users and external reviewers. The organization must ensure that all users comply with these Terms and applicable laws.</p>

        <h2 className="text-body-lg lg:text-h3">5. External Review Access</h2>
        <p className="text-body lg:text-body-lg">External reviewers access content through secure links generated by the organization. Reviewers are granted limited, scoped access to specific assets and may submit feedback or approval decisions within that scope. Organizations are responsible for managing link distribution and ensuring appropriate access control.</p>

        <h2 className="text-body-lg lg:text-h3">6. User Conduct</h2>
        <p className="text-body lg:text-body-lg">You agree not to use the service for unlawful, fraudulent, or abusive purposes. You may not attempt to interfere with system integrity, access data outside your authorized scope, distribute malicious software, reverse engineer the platform, or use the service in a way that disrupts other users. Worklient reserves the right to suspend or terminate accounts that violate these obligations.</p>

        <h2 className="text-body-lg lg:text-h3">7. Content Ownership and License</h2>
        <p className="text-body lg:text-body-lg">All content uploaded to the platform remains the property of the organization or the original rights holder. By uploading content, you grant Worklient a limited, non-exclusive license to host, store, process, and display the content solely for the purpose of operating and improving the service. Worklient does not claim ownership of user content.</p>

        <h2 className="text-body-lg lg:text-h3">8. Approval Records and Audit Logs</h2>
        <p className="text-body lg:text-body-lg">The service maintains structured records of status changes, comments, uploads, and approvals as part of its approval workflow functionality. These activity logs are preserved to support operational traceability and accountability. Organizations acknowledge that such records may be retained for integrity and compliance purposes.</p>

        <h2 className="text-body-lg lg:text-h3">9. Fees and Payment</h2>
        <p className="text-body lg:text-body-lg">If the service is provided under a paid subscription, organizations agree to pay all applicable fees in accordance with the pricing terms presented at the time of purchase. Fees are non-refundable unless otherwise required by law. Failure to pay may result in suspension or termination of access.</p>

        <h2 className="text-body-lg lg:text-h3">10. Data Protection and Privacy</h2>
        <p className="text-body lg:text-body-lg">Worklient processes personal data in accordance with its Privacy Policy. Organizations are responsible for ensuring that they have the lawful right to upload and share personal data through the service. Worklient acts as a service provider with respect to organization-controlled data and processes such data only to deliver the service.</p>

        <h2 className="text-body-lg lg:text-h3">11. Security</h2>
        <p className="text-body lg:text-body-lg">Worklient implements reasonable technical and organizational measures to protect data against unauthorized access, loss, or alteration. While security practices are maintained at industry standards, no system can guarantee absolute security, and users acknowledge inherent risks associated with online services.</p>

        <h2 className="text-body-lg lg:text-h3">12. Availability and Modifications</h2>
        <p className="text-body lg:text-body-lg">Worklient aims to provide reliable and continuous access but does not guarantee uninterrupted or error-free service. We may modify, update, or discontinue features at our discretion. Continued use of the service after updates constitutes acceptance of the revised Terms.</p>

        <h2 className="text-body-lg lg:text-h3">13. Intellectual Property</h2>
        <p className="text-body lg:text-body-lg">All intellectual property rights in the platform, including software, design, trademarks, and documentation, are owned by Worklient or its licensors. You may not copy, modify, distribute, or create derivative works without prior written consent.</p>

        <h2 className="text-body-lg lg:text-h3">14. Disclaimer of Warranties</h2>
        <p className="text-body lg:text-body-lg">The service is provided on an “as is” and “as available” basis. Worklient disclaims all warranties, whether express or implied, including warranties of merchantability, fitness for a particular purpose, and non-infringement.</p>

        <h2 className="text-body-lg lg:text-h3">15. Limitation of Liability</h2>
        <p className="text-body lg:text-body-lg">To the maximum extent permitted by law, Worklient shall not be liable for indirect, incidental, special, consequential, or punitive damages arising from or related to the use of the service. Total liability shall not exceed the fees paid by the organization in the twelve months preceding the claim.</p>

        <h2 className="text-body-lg lg:text-h3">16. Indemnification</h2>
        <p className="text-body lg:text-body-lg">You agree to indemnify and hold harmless Worklient from any claims, damages, or expenses arising out of your misuse of the service, violation of these Terms, or infringement of third-party rights.</p>

        <h2 className="text-body-lg lg:text-h3">17. Termination</h2>
        <p className="text-body lg:text-body-lg">You may discontinue use of the service at any time. Worklient may suspend or terminate access for breach of these Terms or non-payment. Upon termination, access rights cease, and data handling will follow applicable retention policies.</p>

        <h2 className="text-body-lg lg:text-h3">18. Governing Law</h2>
        <p className="text-body lg:text-body-lg">These Terms are governed by the laws of the applicable jurisdiction in which Worklient operates, without regard to conflict of law principles. Any disputes shall be resolved in the competent courts of that jurisdiction.</p>

        <h2 className="text-body-lg lg:text-h3">19. Contact Information</h2>
        <p className="text-body lg:text-body-lg">For questions regarding these Terms, please contact info@worklient.com.</p>
      </Container>
      <FooterSection />
      <JsonLdSEO
        type="WebPage"
        name="Terms of Service | Worklient"
        description="These Terms of Service outline the agreement between you and Worklient regarding your use of our website and services."
        url={CANONICAL_URL}
      />
    </>
  );
}
